name: AutoAnnouncer
main: me.tatteaid.AutoAnnouncer
version: 1.0.0
api-version: 1.16
author: Ambrosia
description: An auto-announcement plugin that provides all of the essentials.

softdepend:
  - PlaceholderAPI

commands:
  announcer:
    description: Displays a helpful guide on how to use AutoAnnouncer.
    usage: /<command> [help/version/author]